### ISSUE TITLE
Docker run failure

### ISSUE THREAD

**Issue by fxzxmic** [codesensegroup/FreenomBot#1]
When running in docker, it prompts that [`./app`](https://github.com/codesensegroup/FreenomBot/blob/1c5caa5d98a3970a3b772bddffb2b877da2b1900/run#L4) cannot be found.
Environment: Alpine 3.12

**Comment by fxzxmic** [comment]
Solved. But there is an associated error that causes the above error.
https://github.com/codesensegroup/FreenomBot/blob/1c5caa5d98a3970a3b772bddffb2b877da2b1900/docker/docker-compose.yml#L8
It should be `/root/app/config.toml`

**Comment by fxzxmic** [comment]
Another Error:
```
/root/app
 2021/01/02 16:22:35 Init
 2021/01/02 16:22:37 log: cookie_id:  *
 2021/01/02 16:22:38 log:  {*}
 panic: runtime error: invalid memory address or nil pointer dereference
 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7968d5]
 
 goroutine 1 [running]:
 github.com/codesensegroup/FreenomBot/internal/line.Send(...)
 	/app/internal/line/line.go:17
 main.task(0xc00000e900, 0x1)
 	/app/FreenomBot.go:20 +0x315
 main.main()
 	/app/FreenomBot.go:33 +0xb6
```

**Comment by frank30941** [comment]
Thank you for using it, I fixed some errors.
please try again.
By the way, I can't believe anyone will use it.
I only develop it for interviews, so there is no double-check.

**Comment by fxzxmic** [comment]
Thank you. It's fixed. But it seems that you didn't package the `resources` folder into the docker image. Besides, it seems that you haven't finished the mailer function.
https://github.com/codesensegroup/FreenomBot/blob/99c1eae1e8ee7862dae8e5f385e9dc6e6189be32/internal/mailer/mailer.go#L21
Here is still the default parameter.

--
PS: 
Looking for related projects on GitHub is almost based on PHP or python. Only this project uses GO language and has complete functions (although you haven't written it, I can see it through the code), and your ideas are very meticulous.

**Comment by frank30941** [comment]
Thanks for your compliment!
Yes, you right. 
When I get free, I will refactor that.
Or If you are interested in Golang, you can also PR this project.
